services:
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8
    volumes:
      - ./volume-data/mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    networks:
      - microservices-net
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql
    networks:
      - microservices-net
  postgresql-credit:
    container_name: pg_sql_credit
    image: postgres
    environment:
      POSTGRES_USER: abraham
      POSTGRES_PASSWORD: abraham
      PGDATA: /data/postgres
    volumes:
      - postgres-credit:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped
  postgresql-branch:
    container_name: pg_sql_branch
    image: postgres
    environment:
      POSTGRES_USER: abraham
      POSTGRES_PASSWORD: abraham
      PGDATA: /data/postgres
    volumes:
      - postgres-branch:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - microservices-net
    restart: unless-stopped
  postgresql-customer:
    container_name: pg_sql_customer
    image: postgres
    environment:
      POSTGRES_USER: abraham
      POSTGRES_PASSWORD: abraham
      PGDATA: /data/postgres
    volumes:
      - postgres-customer:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - microservices-net
    restart: unless-stopped




networks:
  microservices-net:
    driver: bridge

volumes:
  postgres-branch:
  postgres-credit:
  postgres-customer:

