spring:
  config:
    import: optional:configserver:http://localhost:8888
  flyway:
    driver-class-name: org.postgresql.Driver
    enabled: true
    default-schema: public
  application:
    name: gateway-service
